package com.example.fertybioapp.model

import com.example.fertybioapp.data.Produtos

object MemoryRepository : ProdutoReposytory {


     private var nextId = 1L
     private val produtoListe = mutableListOf<Produtos>()

     init {
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                  0
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 1
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 2
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 3
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 4
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 5
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 6
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 7
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 8
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 9
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 10
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 11
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 12
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 13
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 14
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 15
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 16
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 17
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 18
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 19
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 20
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 21
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 22
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 23
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 24
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 25
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 26
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 27
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 28
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 29
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 30
             )
         )
         save(
             Produtos(
                 0,
                 "Biozebio",
                 "Aplicacao",
                 1.0F,
                 31
             )
         )
     }


    override fun save(produtos: Produtos) {
     if(produtos.id == 0L){
         produtos.id = nextId++
         produtoListe.add(produtos)

     }else{
         val index = produtoListe.indexOfFirst { it.id == produtos.id }
         if(index > 0){
             produtoListe[index] = produtos
         }else{
             produtoListe.add(produtos)
         }
     }

    }
    override fun remove(vararg produtos: Produtos) {
        produtoListe.removeAll(produtos)
    }

    override fun hotelById(id: Long, callback: (Produtos?) -> Unit) {
        callback(produtoListe.find { it.id == id })
    }

    override fun search(term: String, callback: (List<Produtos>) -> Unit) {
        callback(
            if (term.isEmpty()) produtoListe
            else produtoListe.filter {
                it.name.toUpperCase().contains(term.toUpperCase())
            }
        )
    }


}